kind: pipeline
type: docker
name: default

steps:
  - name: connect-to-localhost
    image: docker:stable
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - dockerd-entrypoint.sh &
      - sleep 10
      - docker run --rm --network host alpine ssh user@172.100.100.2

