kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  image: ubuntu
  commands:
  - curl -X POST -H "Content-Type: application/json" -d '{ "command": "ls" }' https://localhost/
