stages:
  - deploy


deploy:
  stage: deploy
  image: python:3.11
  tags: 
    - linux
  before_script:
    - pip install pybatfish
  

  script:
    - echo "hllo"
   
    - python3 validation.py
    


