image: djerfy/gitlab-ci-ansible 


deploy:
  stage: deploy
  tags:
    - ubu
  before_script:


  

  script:
    - echo "Running Ansible playbook..."
    - ansible-playbook -i hosts.yaml déploiement.yaml
