stages:
  - deploy


deploy:
  stage: deploy
  image: python:3.11
  tags: 
    - linux
  before_script:
    - pip install pybatfish
    - pip install rich
  

  script:
   
    - python validation.py
    


