stages:
  - deploy

deploy:
  tags:
    - linux
  stage: deploy
  before_script:
    - sudo apt-get update
    - sudo apt-get install -y ansible
    - ssh-keyscan -H 172.100.100.2 >> ~/.ssh/known_hosts
    - ssh-keyscan -H 172.20.20.2 >> ~/.ssh/known_hosts
  script:
    - ansible-playbook -i hosts.yaml déploiement.yaml




