stages:
  - deploy

image: ansible/ansible

deploy:

before_script:
- echo "Installing Ansible..."
- sudo apt-get update
- sudo apt-get install -y ansible

script:
- echo "Running Ansible playbook..."
- ansible-playbook playbook.yml






