stages:
  - deploy

deploy:
  tags:
    - linux
  stage: deploy
  script:
    - apt-get update  # Update package information (for Ubuntu/Debian-based systems)
    - apt-get install -y ansible  # Install Ansible (for Ubuntu/Debian-based systems)
    # Add additional commands here if necessary
    - ansible-playbook -i hosts.yaml déploiement.yaml



