stages:
  - deploy

deploy:
  tags:
    - linux
  stage: deploy
  script:
    - sudo apt-get update
    - sudo apt-get install -y ansible
    - sudo pip install ansible-pylibssh
    - ansible-playbook -i hosts.yaml déploiement.yaml




