[all:vars]
ansible_user=cisco
ansible_ssh_pass=cisco
ansible_become=yes
ansible_become_method=enable
ansible_network_os=ios
ansible_connection=network_cli

[routers]
router1 ansible_host=172.100.100.2
router2 ansible_host=172.20.20.2