name: Self-hosted Runners Example
on:
  push:
    branches:
      - main

jobs:
  run_scripts:
    name: Execute Scripts
    runs-on: self-hosted

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run Script 1
        run: python3 validation.py

      - name: Run Script 2
        run: ./script2.sh

      - name: Run Script 3
        run: ./script3.sh
