name: Deploy to Localhost Devices
on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted  # Specify the label of your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Configuration
        run: |
         ping 172.100.100.2
         ansible-playbook -i hosts.yaml déploiement.yaml
        