name: Deploy to Localhost Devices
on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow o

jobs:
  deploy:
    runs-on: self-hosted  # Specify the label of your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Configuration
        run: |
         ansible-playbook -i hosts.yaml déploiement.yaml
        